version: '3'
services:
  morphovum:
    build: .
    image: dud1337/morphovum
    stdin_open: true
    tty: true
    ports:
      - '8138:8138'
      - '8139:8139'
    volumes:
      - ./samples/music:/fm/music
      - ./samples/ambience:/fm/ambience
      - ./samples/clips:/fm/clips
      - ./samples/playlists:/fm/playlists
      # - /path/to/your/config_dir:/fm/conf
      # config dir should contain config.yaml
    environment:
      - MORPH_OVUM_PASSWORD=changeme # not used if config.yaml provided
      - TZ="Europe/Zurich"
