version: '0.8'
services:
  morphovum:
    #    image: dud1337/morphovum
    build: .
    stdin_open: true
    tty: true
    ports:
      - '8138:8138'
      - '8139:8139'
    volumes:
      - ./samples/music:/fm/music
      - ./samples/ambience:/fm/ambience
      - ./samples/clips:/fm/clips
      - ./samples/playslists:/fm/playlists
    environment:
      - MORPH_OVUM_PASSWORD=changeme
      - TZ="Europe/Zurich"
